services:
  - type: web
    name: predly-api
    runtime: docker
    region: oregon
    branch: predly
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_DEBUG
        value: false